spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/testapp?innodb_lock_wait_timeout=100
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true                     # bật show SQL khi dev cho dễ debug
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: truongnnph49746@gmail.com
    password: ktkmynjeckjsqoig
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

jwt:
  token:
    expiration:
      time: 86400000
    secret: 3G9k7mX4pQ8rT2vW9yZ1aB5cD6eF8gH2jK4mN5pQ7rT9vW0yZ1aB2cD3eF4gH5jK6mN7pQ8rT
    authorization: Authorization
    prefix: Bearer
    refresh:
      expiration:
        time: 86400000

cloudinary:
  cloud-name: dpjudp4iw
  api-key: 891445718184817
  api-secret: QFqkDhHlGWmTLJBVibUFTxEDAOg


logging:
    level:
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG
      com.example.chatappzalo: DEBUG


    spring:
      web:
        resources:
          add-mappings: true
      servlet:
        strict-request-matching: false